name: flutter_slicing_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  google_fonts: ^4.0.3
  ionicons: ^0.2.2
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.1.10
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
